name: ci
on:
  push:
    branches:
      - maintenance
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - maintenance
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.name != 'actions'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.3
        with:
          node-version: "18"
      - run: |
          npm install
          npm run keycloak
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: keycloak_lantbrukare_theme_maintenance
          path: build_keycloak/target/*keycloak-theme*.jar
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  create_github_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
      - run: mkdir jars
      - run: mv keycloak_lantbrukare_theme_maintenance/*keycloak-theme*.jar jars/keycloak-lantbrukare-theme-maintenance.jar
      - uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          # pre_release_branches: develop
          # append_to_pre_release_tag: prerelease
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          files: |
            jars/keycloak-lantbrukare-theme-maintenance.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
