name: CI

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - "kustomize/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUBTOKEN }}

      - name: Identify new version
        uses: mathieudutour/github-tag-action@v5.5
        id: tag_version
        with:
          # pre_release_branches: develop
          # append_to_pre_release_tag: prerelease
          github_token: ${{ secrets.GITHUBTOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag_version.outputs.new_version }}
          labels: ${{ steps.tag_version.outputs.new_version }}

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v2

  #     - name: Setup Kustomize
  #       uses: imranismail/setup-kustomize@v1
  #       with:
  #         kustomize-version: "3.6.1"

  #     - name: Update Kubernetes staging resources
  #       if: ${{ github.ref != 'refs/heads/main' }}
  #       run: |
  #         cd kustomize/overlays/staging
  #         kustomize edit set image agrosphere-api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:'${{ needs.build.outputs.new_version }}'
  #         cat kustomization.yaml

  #     - name: Update Kubernetes production resources
  #       if: ${{ github.ref == 'refs/heads/main' }}
  #       run: |
  #         cd kustomize/overlays/production
  #         kustomize edit set image agrosphere-api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:'${{ needs.build.outputs.new_version }}'
  #         cat kustomization.yaml

  #     - name: Commit files
  #       run: |
  #         git config --local user.email "action@github.com"
  #         git config --local user.name "GitHub Action"
  #         git commit -am "Bump docker tag ${{ needs.build.outputs.new_version }}"

  #     - name: Push changes
  #       uses: ad-m/github-push-action@master
  #       with:
  #         github_token: ${{ secrets.GITHUBTOKEN }}
  #         branch: ${{ github.ref }}
