name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.name != 'actions'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.3
        with:
          node-version: "18"
      - run: |
          yarn install
          yarn run build-keycloak-theme
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare release JAR
        run: |
          # Remove the Keycloak 22-25 specific JAR
          rm -f dist_keycloak/keycloak-theme-for-kc-22-to-25.jar
          
          # Keep only the universal JAR for artifact upload
          # It will be renamed with version during release
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar

  create_github_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
      - uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          dry_run: ${{ github.event_name == 'pull_request' }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Rename JAR with version
        run: |
          # Extract version number from tag (remove 'v' prefix if present)
          VERSION=${{ steps.tag_version.outputs.new_version }}
          
          # Rename the JAR file with the version
          mv artifacts/keycloak-theme-for-kc-all-other-versions.jar \
             artifacts/keycloak-lantbrukare-theme-${VERSION}.jar
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          files: |
            artifacts/keycloak-lantbrukare-theme-*.jar
          prerelease: ${{ github.event_name == 'pull_request' }}
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
